'use client';
import { useEffect, useState } from 'react';
import { Action, initialActions, parseActions, pickAction, STORAGE_KEY } from '../lib/actions';
export default function Home() {
 const [actions,setActions]=useState<Action[]>([]);
 const [ready,setReady]=useState(false);
 const [result,setResult]=useState<Action|null>(null);
 const [message,setMessage]=useState('');
 const [editing,setEditing]=useState<string|null>(null);
 const [title,setTitle]=useState(''); const [minutes,setMinutes]=useState('15');
 const [place,setPlace]=useState<'indoor'|'outdoor'>('indoor'); const [note,setNote]=useState('');
 useEffect(()=>{try {const raw=localStorage.getItem(STORAGE_KEY); setActions(raw===null ? initialActions : parseActions(raw));} catch {setMessage('保存データを読み込めませんでした。候補を追加して再保存できます。');} setReady(true);},[]);
 function persist(next:Action[]) {setActions(next); try {localStorage.setItem(STORAGE_KEY,JSON.stringify(next));setMessage('この端末に保存しました。');} catch {setMessage('端末への保存に失敗しました。再読み込みすると変更が失われる可能性があります。');}}
 function resetForm(){setEditing(null);setTitle('');setMinutes('15');setPlace('indoor');setNote('');}
 function submit(e:React.FormEvent){e.preventDefault();const n=Number(minutes);if (!title.trim() || title.trim().length>80 || !Number.isInteger(n) || n<1 || n>1440) {setMessage('候補名と1〜1440分の整数を入力してください。');return;} const item:Action={id:editing??crypto.randomUUID(),title:title.trim(),minutes:n,place,note:note.trim()};persist(editing?actions.map(a=>a.id===editing?item:a):[...actions,item]);if(result?.id===editing)setResult(item);resetForm();}
 function edit(a:Action){setEditing(a.id);setTitle(a.title);setMinutes(String(a.minutes));setPlace(a.place);setNote(a.note);document.getElementById('action-title')?.focus();}
 function remove(a:Action){if(!window.confirm(`「${a.title}」を削除しますか？`))return;persist(actions.filter(x=>x.id!==a.id));if(result?.id===a.id)setResult(null);if(editing===a.id)resetForm();}
 function suggest(){setResult(pickAction(actions));setMessage(actions.length?'候補からランダムに選びました。':'まずは行動候補をひとつ追加してください。');}
 return <main>
 <header><a className="brand" href="/">暇な君へ<span className="brand-dot">●</span></a><a className="nav" href="#my-actions">自分の候補 ↗</a></header>
 <section className="hero"><div className="intro"><span className="eyebrow">A LITTLE NUDGE FOR YOUR DAY</span><h1>なにしよう。<br/>その先の、<em>一歩へ。</em></h1><p className="lead">予定のない時間も、あなたの時間。<br/>迷ったら、次にすることをひとつ決めよう。</p><div className="hint"><span>✦</span> 選ぶのを、ちょっとおまかせ。</div></div>
 <div className="suggestion"><div className="card-top"><span>YOUR NEXT MOVE</span><span className="pill">{ready?`${actions.length}件の候補`:'読み込み中'}</span></div><div className="orb" aria-hidden="true">↗</div><div className="result" aria-live="polite">{result?<><div className="result-meta">{result.place==='indoor'?'室内で':'外に出て'} · 約{result.minutes}分</div><h2>{result.title}</h2><p>{result.note||'まずは小さく、始めてみよう。'}</p></>:<><h2>{ready&&!actions.length?'あなたの候補を追加しよう':'今日の余白に、何をする？'}</h2><p>ボタンを押すと、登録した候補から<br/>行動をひとつ提案します。</p></>}</div><button className="primary" disabled={!ready||!actions.length} onClick={suggest}>{result?'もう一度、提案してもらう':'いま、何しよう？'} <span>↗</span></button><small>登録した候補からランダムに選びます</small></div></section>
 <section className="workspace" id="my-actions"><div className="section-heading"><div><span className="eyebrow">MAKE IT YOURS</span><h2>自分の「やってみたい」を集めよう。</h2></div><p>いつものことも、気になることも。</p></div><div className="columns"><form onSubmit={submit} className="form-card"><h3>{editing?'候補を編集する':'候補をひとつ追加'}</h3><label htmlFor="action-title">何をする？</label><input id="action-title" value={title} onChange={e=>setTitle(e.target.value)} maxLength={80} required placeholder="例：積んでいた本を10ページ読む"/><div className="form-row"><div><label htmlFor="minutes">目安の時間（分）</label><input id="minutes" type="number" min="1" max="1440" step="1" value={minutes} onChange={e=>setMinutes(e.target.value)} required/></div><div><label htmlFor="place">場所</label><select id="place" value={place} onChange={e=>setPlace(e.target.value as Action['place'])}><option value="indoor">室内</option><option value="outdoor">屋外</option></select></div></div><label htmlFor="note">ひとことメモ（任意）</label><textarea id="note" value={note} onChange={e=>setNote(e.target.value)} maxLength={200} placeholder="始めやすくなる、小さなヒント。"/><button className="secondary" disabled={!ready}>{editing?'変更を保存':'候補を追加'} <span>＋</span></button>{editing&&<button className="cancel" type="button" onClick={resetForm}>編集をキャンセル</button>}<p className="storage-note">候補はこのブラウザーに保存されます。別の端末との同期はまだありません。</p></form><div className="list-panel"><div className="list-heading"><h3>あなたの行動リスト</h3><span>{actions.length} IDEAS</span></div>{ready&&actions.length===0?<div className="empty">まだ候補がありません。<br/>気軽にできることから追加してみよう。</div>:actions.map((a,i)=><article className="action" key={a.id}><span className="number">{String(i+1).padStart(2,'0')}</span><div className="action-body"><h4>{a.title}</h4><p>{a.place==='indoor'?'室内':'屋外'} <span>·</span> 約{a.minutes}分</p></div><div className="action-buttons"><button onClick={()=>edit(a)} aria-label={`${a.title}を編集`}>編集</button><button onClick={()=>remove(a)} aria-label={`${a.title}を削除`}>削除</button></div></article>)}</div></div></section><p className="status" role="status">{message}</p><footer><span>暇な君へ</span><p>余白から、はじめよう。</p><small>天気・位置情報による提案は、今後追加予定です。</small></footer>
 </main>;
}
